function MetaData = importVideoTextFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SOFTTESTRUN1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  SOFTTESTRUN1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SoftTestrun1 = importfile("C:\Users\Xiangnan\OneDrive - University of California, Davis\UC Davis\Paper&Grant\My Paper\2020 APD Paper\Data\20200831ImagingTest\20200831SoftTest\txt\20200831SoftTest_run10.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2020 15:11:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
SoftTestrun1 = readtable(filename, opts);

%% Convert to output type
MetaData = table2array(SoftTestrun1);
end