function [Frame1, x, y] = importPos(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [FRAME1, X, Y] = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as column vectors.
%
%  [FRAME1, X, Y] = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  [FRAME1, X, Y] = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Frame1, x, y] = importfile("C:\Users\Xiangnan\Box\Prostate Pilot\RARPDatabase\RARP_P3\videos\MC\RARP_P3_Run1.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Oct-2025 22:47:22

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Frame1", "x", "y"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
RARP_P3_Run1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RARP_P3_Run1 = [RARP_P3_Run1; tb]; %#ok<AGROW>
end

%% Convert to output type
Frame1 = RARP_P3_Run1.Frame1;
x = RARP_P3_Run1.x;
y = RARP_P3_Run1.y;
end