function [Frame, PointIndex, X, Y] = importAllFrame(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [FRAME, POINTINDEX, X, Y] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [FRAME, POINTINDEX, X, Y] = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Frame, PointIndex, X, Y] = importfile("C:\Users\Xiangnan\Box\Prostate Pilot\RARPDatabase\RARP_P3\videos\MC\RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Oct-2025 20:08:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Frame", "PointIndex", "X", "Y"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames = readtable(filename, opts);

%% Convert to output type
Frame = RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames.Frame;
PointIndex = RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames.PointIndex;
X = RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames.X;
Y = RARP_P3_run1_Motion_Corrected_Coordinates_AllFrames.Y;
end