function [bestShift, fitresult, gof] = findShift(shift, res)
%CREATEFIT(SHIFT,D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: shift
%      Y Output: D
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jul-2024 22:37:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( shift, res );

% Set up fittype and options.
ft = fittype( 'poly4' );

opts = fitoptions( 'Method', 'LinearLeastSquares' );


% Fit model to data.
try
[fitresult, gof] = fit( xData, yData, ft, opts );
shift_2 = min(shift):0.05:max(shift);
res_interp = fitresult(shift_2);
[~,I] = min(res_interp);
bestShift = shift_2(I);
catch
    bestShift = 0;
end
% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'D vs. shift', 'residual fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'shift', 'Interpreter', 'none' );
% ylabel( 'D', 'Interpreter', 'none' );
% grid on


