clear
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Xiangnan\Desktop\H&N Aggregate Input Data - Run_Level.csv
%
% Auto-generated by MATLAB on 13-Oct-2022 14:14:51

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Patients", "Run", "Scan Context", "Motion Correction Performed", "Anatomy", "MC Reference Frame", "Include in Analysis", "Deconvolution File", "Text File", "Video Path", "Non-MC Corrected Positions", "Refined Positions", "Annotation File", "Reference Frame WLI"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "categorical", "double", "categorical", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Deconvolution File", "Text File", "Video Path", "Non-MC Corrected Positions", "Refined Positions", "Annotation File", "Reference Frame WLI"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Scan Context", "Motion Correction Performed", "Anatomy", "MC Reference Frame", "Include in Analysis", "Deconvolution File", "Text File", "Video Path", "Non-MC Corrected Positions", "Refined Positions", "Annotation File", "Reference Frame WLI"], "EmptyFieldRule", "auto");

% Import the data
HN = readtable("H&N Aggregate Input Data - Run_Level.csv", opts);


%% Clear temporary variables
clear opts

%% filter out FLImBRSUH data
T = HN(HN.Patients>100,:);
root = 'N:\V2 Sacramento Database\Da Vinci Robot Study (100 patients)\Data_100_Patient_Study';

%%
for i=4
    
    temp = T.DeconvolutionFile{i};
    matName = fullfile(root,temp)
%     temp(1) = 'W';
    ReprocessFB(matName)
    
end

