clear
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Xiangnan\Desktop\H&N Aggregate Input Data - Run_Level.csv
%
% Auto-generated by MATLAB on 13-Oct-2022 14:14:51

opts = delimitedTextImportOptions("NumVariables", 26);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Patient", "Run", "ScanContext", "Anatomy", "MCReferenceFrame", "DataChannelsUsed", "IncludeInAnalysis", "RawFLImDataFiletdms", "BackgroundFile", "DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName17", "HistopathologyOrder", "Deconvolution", "ABPositionCorrection", "InstrumentSegmentation", "MotionCorrection", "HistopathologyCoregistration", "AnnotationMask", "ReprocessingDeconvolution", "OtherNotes"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "double", "double", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "categorical", "categorical", "string", "categorical", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["RawFLImDataFiletdms", "BackgroundFile", "DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName17", "HistopathologyOrder", "Deconvolution", "ABPositionCorrection", "HistopathologyCoregistration", "OtherNotes"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ScanContext", "Anatomy", "IncludeInAnalysis", "RawFLImDataFiletdms", "BackgroundFile", "DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName17", "HistopathologyOrder", "Deconvolution", "ABPositionCorrection", "InstrumentSegmentation", "MotionCorrection", "HistopathologyCoregistration", "AnnotationMask", "ReprocessingDeconvolution", "OtherNotes"], "EmptyFieldRule", "auto");

% Import the data
HN = readtable("C:\Users\MarcuAdmin\Documents\GitHub\FLImBrushDataProcessingTool\AdcancedFunctions\H&N Aggregate Input Data - Run_Level 20231206.csv", opts);
%% Clear temporary variables
clear opts

%% filter out FLImBRUSH data
T = HN((HN.Patient>137)&(HN.Patient<190),:);
root = 'E:\V2_Sacramento_Database\Da Vinci Robot Study (100 patients)\Data_100_Patient_Study';
saveRootPath = 'C:\Users\MarcuAdmin\Documents\Data\BatchProcess';

%%
for i=20:size(T,1)
    
    tempfile = T.DeconvolutionFile{i};
    if ~isempty(tempfile)
%    [path, name, ext] = fileparts(tempfile);e
%    tempfile = strcat(path, '\', name, '_lite', ext);
    matName = fullfile(root,tempfile)
%     temp(1) = 'W';
    %ReprocessFB_KE(matName, saveRootPath)
    ReprocessFB_KEplot(matName, saveRootPath)
    end
end

