clear
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Xiangnan\Desktop\H&N Aggregate Input Data - Run_Level.csv
%
% Auto-generated by MATLAB on 13-Oct-2022 14:14:51

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Patient", "Run", "ScanContext", "MotionCorrectionPerformed", "Anatomy", "MCReferenceFrame", "DataChannelsUsed", "IncludeInAnalysis", "DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName16", "HistopathologyRegistered", "AnnotationTool", "DeconvolutionPerformed", "PositionCorrected", "MotionCorrected", "OtherNotes"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "categorical", "double", "categorical", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "categorical", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName16", "HistopathologyRegistered", "DeconvolutionPerformed", "PositionCorrected", "MotionCorrected", "OtherNotes"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ScanContext", "MotionCorrectionPerformed", "Anatomy", "DataChannelsUsed", "IncludeInAnalysis", "DeconvolutionFile", "TextFile", "VideoPath", "NonMCCorrectedPositions", "RefinedPositions", "AnnotationFile", "ReferenceFrameWLI", "VarName16", "HistopathologyRegistered", "AnnotationTool", "DeconvolutionPerformed", "PositionCorrected", "MotionCorrected", "OtherNotes"], "EmptyFieldRule", "auto");


% Import the data
HN = readtable("E:\MyGitRepo\FLImBrushDataProcessingTool\AdcancedFunctions\H&N Aggregate Input Data - Run_Level 20230413.csv", opts);
%% Clear temporary variables
clear opts

%% filter out FLImBRSUH data
T = HN((HN.Patient>154)&(HN.Patient<173),:);
root = 'Z:\V2 Sacramento Database\Da Vinci Robot Study (100 patients)\Data_100_Patient_Study';

%%
for i=1:size(T,1)
    
    temp = T.DeconvolutionFile{i};
    if ~isempty(temp)
    matName = fullfile(root,temp)
%     temp(1) = 'W';
    ReprocessFB(matName)
    end
end

