function BkgdreviewApril16 = importBGReview(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  BKGDREVIEWAPRIL16 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  BKGDREVIEWAPRIL16 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  BKGDREVIEWAPRIL16 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  BkgdreviewApril16 = importfile("E:\MyGitRepo\FLImBrushDataProcessingTool\AdcancedFunctions\Bkgd-review-April_16.xlsx", "Sheet1", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Apr-2024 10:49:32

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Patient", "Run", "ScanContext", "BkdgCh1", "BkdgCh2", "BkdgCh3", "selectNewBkgd", "backgroundTruncationyn", "CFDyn"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["ScanContext", "BkdgCh1", "BkdgCh2", "BkdgCh3", "selectNewBkgd", "backgroundTruncationyn", "CFDyn"], "EmptyFieldRule", "auto");

% Import the data
BkgdreviewApril16 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    BkgdreviewApril16 = [BkgdreviewApril16; tb]; %#ok<AGROW>
end

end